// Demo/placeholder data. Replace with live fetches to the Express API
// (see lib/api.js) once the backend is seeded.

export const CATEGORIES = [
  {
    name: 'Фитинги',
    slug: 'fittings',
    icon: 'Wrench',
    subcategories: ['Компрессионные', 'Пресс-фитинги', 'Переходники'],
  },
  {
    name: 'Трубы',
    slug: 'pipes',
    icon: 'PipetteIcon',
    subcategories: ['Металлопластиковые', 'Полипропиленовые', 'Гибкие трубы'],
  },
  {
    name: 'Канализационные трубы',
    slug: 'sewer-pipes',
    icon: 'Droplets',
    subcategories: ['Дренажные', 'Фекальные', 'Напорные'],
  },
  {
    name: 'PPR трубы',
    slug: 'ppr-pipes',
    icon: 'PipetteIcon',
    subcategories: ['PN10', 'PN16', 'PN20'],
  },
  {
    name: 'Водяные бойлеры',
    slug: 'water-boilers',
    icon: 'Thermometer',
    subcategories: ['Электрические', 'Накопительные', 'Проточные'],
  },
  {
    name: 'Радиаторы отопления',
    slug: 'radiators',
    icon: 'AlignJustify',
    subcategories: ['Алюминиевые', 'Биметаллические', 'Стальные'],
  },
  {
    name: 'Системы водоснабжения',
    slug: 'water-supply',
    icon: 'Waves',
    subcategories: ['Резервуары', 'Коллекторы', 'Комплекты'],
  },
  {
    name: 'Комплектующие для труб',
    slug: 'pipe-fittings',
    icon: 'GitBranch',
    subcategories: ['Муфты', 'Отводы', 'Тройники'],
  },
  {
    name: 'Краны и клапаны',
    slug: 'taps-valves',
    icon: 'Wrench',
    subcategories: ['Краны', 'Шаровые клапаны', 'Регуляторы'],
  },
  {
    name: 'Сантехнические аксессуары',
    slug: 'plumbing-accessories',
    icon: 'Droplets',
    subcategories: ['Заглушки', 'Хомуты', 'Крепления'],
  },
];

export const BRANDS = ['Valtec', 'Wavin', 'Uponor', 'Henco', 'Roca', 'Kohler', 'Aqua'];

export const PRODUCTS = [
  {
    sku: 'VT-FIT-20-CR',
    slug: 'valtec-compression-fitting-20mm',
    title: 'Компрессионный фитинг Valtec 20 мм',
    brand: 'Valtec',
    category: 'fittings',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    price: 22000,
    discountPrice: 18000,
    stock: 140,
    unit: 'pcs',
    specifications: { diameter: '20mm' },
    isHotDeal: true,
    description: 'Надёжный компрессионный фитинг для систем горячего и холодного водоснабжения.',
  },
  {
    sku: 'WVN-PIP-25',
    slug: 'wavin-pipe-25mm',
    title: 'Труба Wavin 25 мм для водоснабжения',
    brand: 'Wavin',
    category: 'pipes',
    image: 'https://images.unsplash.com/photo-1621905251918-48416bd8575a?auto=format&fit=crop&w=1200&q=80',
    price: 46000,
    stock: 220,
    unit: 'meters',
    specifications: { diameter: '25mm' },
    isHotDeal: false,
    description: 'Гибкая высокопрочная труба для внутренней разводки и подключения сантехнических узлов.',
  },
  {
    sku: 'HNC-SW-110',
    slug: 'henco-sewer-pipe-110mm',
    title: 'Канализационная труба Henco 110 мм',
    brand: 'Henco',
    category: 'sewer-pipes',
    image: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
    price: 68000,
    stock: 98,
    unit: 'meters',
    specifications: { diameter: '110mm' },
    isHotDeal: false,
    description: 'Надёжная канализационная труба для наружных и внутренних стояков.',
  },
  {
    sku: 'UPN-PPR-32',
    slug: 'uponor-ppr-pipe-32mm',
    title: 'PPR труба Uponor 32 мм PN16',
    brand: 'Uponor',
    category: 'ppr-pipes',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&q=80',
    price: 76000,
    discountPrice: 61000,
    stock: 180,
    unit: 'meters',
    specifications: { diameter: '32mm' },
    isHotDeal: true,
    description: 'Прочная полипропиленовая труба для горячей и холодной воды по системам PN16.',
  },
  {
    sku: 'AQU-BOIL-50',
    slug: 'aqua-electric-water-boiler-50l',
    title: 'Электрический водонагреватель Aqua 50 л',
    brand: 'Aqua',
    category: 'water-boilers',
    image: 'https://images.unsplash.com/photo-1620626011761-996317b8d101?auto=format&fit=crop&w=1200&q=80',
    price: 11800000,
    stock: 40,
    unit: 'pcs',
    specifications: { volume: '50L' },
    isHotDeal: false,
    description: 'Накопительный электрический бойлер для квартиры и частного дома.',
  },
  {
    sku: 'ROC-RAD-500',
    slug: 'roca-aluminum-radiator-500',
    title: 'Алюминиевый радиатор Roca 500 мм',
    brand: 'Roca',
    category: 'radiators',
    image: 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=80',
    price: 540000,
    stock: 28,
    unit: 'pcs',
    specifications: { size: '500mm' },
    isHotDeal: false,
    description: 'Компактный алюминиевый радиатор с высокой теплоотдачей и стильным дизайном.',
  },
  {
    sku: 'KOH-COL-3',
    slug: 'kohler-water-supply-collector-3-way',
    title: 'Коллектор систем водоснабжения Kohler 3-ходовой',
    brand: 'Kohler',
    category: 'water-supply',
    image: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    price: 990000,
    stock: 12,
    unit: 'pcs',
    specifications: { type: '3-way' },
    isHotDeal: false,
    description: 'Равномерное распределение потоков воды по зонам и удобный контроль давления.',
  },
  {
    sku: 'VT-PIPE-TEE-25',
    slug: 'valtec-tee-branch-25mm',
    title: 'Тройник Valtec 25 мм для труб',
    brand: 'Valtec',
    category: 'pipe-fittings',
    image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',
    price: 32000,
    stock: 90,
    unit: 'pcs',
    specifications: { diameter: '25mm' },
    isHotDeal: false,
    description: 'Тройник для аккуратного соединения двух линий в одной точке сети.',
  },
  {
    sku: 'HNC-VALVE-1',
    slug: 'henco-ball-valve-1-inch',
    title: 'Шаровый кран Henco 1 дюйм',
    brand: 'Henco',
    category: 'taps-valves',
    image: 'https://images.unsplash.com/photo-1620226011175-8a3d4d8980aa?auto=format&fit=crop&w=1200&q=80',
    price: 79000,
    stock: 52,
    unit: 'pcs',
    specifications: { diameter: '1"' },
    isHotDeal: false,
    description: 'Надёжный шаровый кран с быстрым перекрытием и плотным уплотнением.',
  },
  {
    sku: 'ROC-ACC-SET',
    slug: 'roca-plumbing-accessories-kit',
    title: 'Комплект сантехнических аксессуаров Roca',
    brand: 'Roca',
    category: 'plumbing-accessories',
    image: 'https://images.unsplash.com/photo-1494526585095-c41746248156?auto=format&fit=crop&w=1200&q=80',
    price: 470000,
    stock: 24,
    unit: 'pcs',
    specifications: { set: 'Complete' },
    isHotDeal: false,
    description: 'Универсальный набор креплений, заглушек и соединительных элементов для монтажа.',
  },
  {
    sku: 'UPN-COND-20',
    slug: 'uponor-pipe-connector-20mm',
    title: 'Муфта Uponor 20 мм для трубы',
    brand: 'Uponor',
    category: 'pipe-fittings',
    image: 'https://images.unsplash.com/photo-1581092918056-0c4c3acd3789?auto=format&fit=crop&w=1200&q=80',
    price: 28000,
    stock: 110,
    unit: 'pcs',
    specifications: { diameter: '20mm' },
    isHotDeal: false,
    description: 'Плотное и долговечное соединение для систем подпитки и распределения воды.',
  },
  {
    sku: 'AQU-BOIL-80',
    slug: 'aqua-electric-water-boiler-80l',
    title: 'Электрический бойлер Aqua 80 л',
    brand: 'Aqua',
    category: 'water-boilers',
    image: 'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',
    price: 14600000,
    stock: 18,
    unit: 'pcs',
    specifications: { volume: '80L' },
    isHotDeal: true,
    description: 'Классический накопительный электрический водонагреватель для надёжной подачи тёплой воды.',
  },
  {
    sku: 'WVN-PEX-16',
    slug: 'wavin-pex-pipe-16mm',
    title: 'Металлопластиковая труба Wavin 16 мм',
    brand: 'Wavin',
    category: 'pipes',
    image: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1200&q=80',
    price: 34000,
    stock: 300,
    unit: 'meters',
    specifications: { diameter: '16mm' },
    isHotDeal: false,
    description: 'Гибкая труба для скрытой разводки в системах холодного и горячего водоснабжения.',
  },
];

export const HOT_DEALS = PRODUCTS.filter((p) => p.isHotDeal);

export const FITTINGS_MATRIX = {
  PEX: {
    16: [
      { name: 'Компрессионный фитинг 16 мм', sku: 'FIT-PEX16-CR', price: 18000 },
      { name: 'Переходник 16 мм x 1/2"', sku: 'FIT-PEX16-PA', price: 24000 },
      { name: 'Шаровый кран 16 мм', sku: 'FIT-PEX16-BV', price: 45000 },
    ],
    20: [
      { name: 'Компрессионный фитинг 20 мм', sku: 'FIT-PEX20-CR', price: 21000 },
      { name: 'Переходник 20 мм x 3/4"', sku: 'FIT-PEX20-PA', price: 27000 },
      { name: 'Кран 20 мм', sku: 'FIT-PEX20-BV', price: 52000 },
      { name: 'Коллектор 20 мм', sku: 'FIT-PEX20-MN4', price: 210000 },
    ],
    25: [
      { name: 'Компрессионный фитинг 25 мм', sku: 'FIT-PEX25-CR', price: 26000 },
      { name: 'Переходник 25 мм x 1"', sku: 'FIT-PEX25-PA', price: 33000 },
      { name: 'Шаровый клапан 25 мм', sku: 'FIT-PEX25-BV', price: 61000 },
    ],
  },
  PPR: {
    20: [
      { name: 'Муфта PPR 20 мм', sku: 'FIT-PPR20-CP', price: 6000 },
      { name: 'Отвод PPR 90° 20 мм', sku: 'FIT-PPR20-EL', price: 5500 },
      { name: 'Кран PPR 20 мм', sku: 'FIT-PPR20-BV', price: 38000 },
    ],
    25: [
      { name: 'Муфта PPR 25 мм', sku: 'FIT-PPR25-CP', price: 7500 },
      { name: 'Тройник PPR 25 мм', sku: 'FIT-PPR25-TE', price: 8200 },
      { name: 'Кран PPR 25 мм', sku: 'FIT-PPR25-BV', price: 44000 },
    ],
    32: [
      { name: 'Муфта PPR 32 мм', sku: 'FIT-PPR32-CP', price: 9800 },
      { name: 'Отвод PPR 90° 32 мм', sku: 'FIT-PPR32-EL', price: 9200 },
    ],
  },
  'Metal-Plastic': {
    16: [
      { name: 'Компрессионный фитинг 16 мм', sku: 'FIT-MP16-CO', price: 19500 },
      { name: 'Латунная муфта 16 мм', sku: 'FIT-MP16-CR', price: 20500 },
    ],
    20: [
      { name: 'Компрессионный фитинг 20 мм', sku: 'FIT-MP20-CO', price: 23500 },
      { name: 'Кран 20 мм', sku: 'FIT-MP20-BV', price: 51000 },
      { name: 'Коллектор 20 мм', sku: 'FIT-MP20-MN3', price: 165000 },
    ],
    26: [
      { name: 'Компрессионный фитинг 26 мм', sku: 'FIT-MP26-CO', price: 29000 },
      { name: 'Кран 26 мм', sku: 'FIT-MP26-BV', price: 58000 },
    ],
  },
};

export const PIPE_MATERIALS = Object.keys(FITTINGS_MATRIX);
